### ISSUE TITLE
QWebDav version

### ISSUE THREAD

**Issue by vaskas** [doctorrokter/ya_disk#1]
Hi Mikhail, thank you for making so many great BB10 applications. Really appreciate you having released the source code! I am trying to tweak the code to adapt it to NextCloud and can see that the QWebDav library code is slightly different from the version at https://github.com/mhaller/qwebdavlib. Could you please explain whether you enhanced the upstream library - or it's some other version you are using? I am also trying to understand whether YaDisk is really different from any other WebDav server.

**Comment by doctorrokter** [comment]
@vaskas Hey! 
Yes, I did some changes into initial library. I don't remember exactly, but I wanted to cover full Yandex Webdav API and decided to do it in webdav core library (which is pretty old).

I'm not sure does other webdav services support `partial loading`, `publish/unpublish` dirs, downloading `previews` etc.

You can examine what and why was changed by commit comments, some of them are pretty self-explanatory:
![image](https://user-images.githubusercontent.com/8337018/115348913-e487e680-a1bb-11eb-93c6-5106ef263c05.png)

**Comment by vaskas** [comment]
Thank you - I should be using git for what it's designed for :rofl: Also what are your views on the license for the YaDisk source code? I have so far slapped something together that can upload files into Nextcloud and browse the root directory (subdirs are broken) but it all looks promising.

**Comment by doctorrokter** [comment]
@vaskas I added `LICENSE` file and selected `MIT` type. Feel free to copy/use/embed any part of the code!

**Comment by vaskas** [comment]
You are awesome, thank you!
